### ISSUE TITLE
能否加入命令行方式控制播放暂停，选曲，方便自动化调用

### ISSUE THREAD

**Issue by tonywk** [Louie-v/MyMusicBox#5]
如果能加入命令行控制，无论是shell 命令行参数还是 curl调用网址的方式都可以，这样就可以通过无穷的方式把音乐播放功能集成到很多应用场景当中。我是想把它用到一些智能家居应用场景当中，比如早上起床放音乐。
多谢

**Comment by Louie-v** [comment]
其实我也是这样计划的，只是时间和能力有限，其实你只需要看一下index.py或者app.js就能明白怎么用curl进行调用，但是用curl会显得复杂。后期有时间了看能不能再完善，然后写一个REST接口

**Comment by tonywk** [comment]
谢谢，我研究一下。如果有时间完善更好！
